server:
  build: ./ngrok
  container_name: ngrokd
  restart: always
  ports:
    - "8880:80"
    - "8443:443"
    - "4443:4443"
  volumes:
    - /data/ngrok:/myfiles
  environment:
    - DOMAIN=ngrok.gudqs.cn
  command: /bin/sh /server.sh
